language: python
python:
  - "2.7"
install:
  - sudo apt-get install pandoc -y
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install git+git://github.com/tbabej/django-avatar
  - pip install git+git://github.com/django-wiki/django-wiki
  - cp roots/local_settings.py.in roots/local_settings.py
  - cp -r templates_custom.in templates_custom
  - python manage.py collectstatic --noinput
script:
  - coverage run --source=. manage.py test
after_script:
  - coveralls
