language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - cp roots/local_settings.py.in roots/local_settings.py
script:
  - coverage run --source=. manage.py test
after_script:
  - coveralls
